// <auto-generated />
using System;
using AssadosCombate_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssadosCombate_API.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20231002002007_AddTablePedido")]
    partial class AddTablePedido
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AssadosCombate_API.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Contato")
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AssadosCombate_API.Models.Item_Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Item_Pedido");
                });

            modelBuilder.Entity("AssadosCombate_API.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemPedidoId")
                        .HasColumnType("int");

                    b.Property<string>("ValorTotal")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ItemPedidoId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("AssadosCombate_API.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Preco")
                        .HasColumnType("longtext");

                    b.HasKey("ProdutoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("AssadosCombate_API.Models.Item_Pedido", b =>
                {
                    b.HasOne("AssadosCombate_API.Models.Produto", "produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId");

                    b.Navigation("produto");
                });

            modelBuilder.Entity("AssadosCombate_API.Models.Pedido", b =>
                {
                    b.HasOne("AssadosCombate_API.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("AssadosCombate_API.Models.Item_Pedido", "ItemPedido")
                        .WithMany()
                        .HasForeignKey("ItemPedidoId");

                    b.Navigation("Cliente");

                    b.Navigation("ItemPedido");
                });
#pragma warning restore 612, 618
        }
    }
}
