
POST http://localhost:5074/api/Cliente/post
Content-Type: application/json

{ 
  "nome": "Luiz",
  "contato": "41991787723",
  "endereco": "av das torres"
}

### get all addresses 
GET http://localhost:5074/api/Cliente/getAll


### search by ID or NAME, but it's not searching
GET http://localhost:5074/api/Cliente/getByNome/Luiz

### update an existing address by ID 
PUT http://localhost:5074/api/Cliente/9
Content-Type: application/json

{ 
  "nome": "Luiz",
  "contato": "41 991898702",
  "endereco": "Av Anita Garibaldi"
}


### deletion of a address by ID
DELETE http://localhost:5074/api/Cliente/9